# Build a REST API with FastAPI and Python
# Source: https://fastapi.tiangolo.com/tutorial/first-steps/
# Generated by BuildBridge

print("Starting: Build a REST API with FastAPI and Python")

# Step 1: Create and activate a virtual environment
